In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\Khushi\[XB3421] Data Extraction For USA Counties_Virec\us\arizona\maricopa\prop\Raw_Data\us_az_04013_data_prop_main_bronze_20260701.csv")
df

,Parcel,Property_Address,city,zipcode,MCR_#,Description,Lat/Long,Lot_Size,Lot_#,High_School_District,...,Subdivision,Owner_Name,Mailing_Address,Deed_Number,Last_Deed_Date,Sale_Date,Sale_Price,In_Care_Of,Fee_Owner,Page_Save
0,10101001C,", AZ",NaN,NaN,NaN,PT SW4 SEC 7 DAF COM SW COR SD SEC 7 TH N 459....,|,"7,565 sq ft.",NaN,TOLLESON UNION #214,...,NaN,EL PASO NATURAL GAS COMPANY,"PO BOX 4372, HOUSTON, TX 77210",20090011877,01/07/2009,NaN,NaN,NaN,NaN,10101001C.html
1,10101002G,", AZ",NaN,NaN,NaN,TH POR SE4 SEC 7 DAF COM E4 COR SD SEC 7 TH W ...,|,"63,173 sq ft.",NaN,TOLLESON UNION #214,...,NaN,UNITED STATES BUREAU OF RECLAMATION,"201 N CENTRAL STE 2100, PHOENIX, AZ 85073",20050287974,03/09/2005,NaN,NaN,NaN,NaN,10101002G.html
2,10101004R,", AZ",NaN,NaN,NaN,NW4 SEC 7 EX N 78F OF W 78F TH/OF and EX W 65F...,|,"3,437,319 sq ft.",NaN,TOLLESON UNION #214,...,NaN,LATERAL 25 LAND CO LLC,"134 E PALM LN, PHOENIX, AZ 85004",20121190440,12/31/2012,NaN,NaN,NaN,NaN,10101004R.html
3,10101008B,"11328 W BUCKEYE RD AVONDALE, AZ 85323",NaN,85323.0,NaN,TH PT SW4 SEC 7 T1N R1E DAF COM SW COR SEC TH ...,|,"529,389 sq ft.",NaN,TOLLESON UNION #214,...,NaN,11328 BUCKEYE ROAD LLC,"4800 N SCOTTSDALE RD 4300, SCOTTSDALE, AZ 85027",20220683622,08/31/2022,NaN,NaN,NaN,NaN,10101008B.html
4,10101009,", AZ",NaN,NaN,64207.0,AVONDALE CIVIC CENTER MCR 642-07,|,"107,766 sq ft.",1,TOLLESON UNION #214,...,AVONDALE CIVIC CENTER,AVONDALE CITY OF,"11465 W CIVIC CENTER DR STE 2, AVONDALE, AZ 85...",20030869328,07/02/2003,07/01/2003,NaN,NaN,NaN,10101009.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726981,51016307,", AZ",NaN,NaN,175341.0,175341 CYRENE AT MYSTIC FOOTHILLS,|,"1,590 sq ft.",NaN,PEORIA UNIFIED EXT 3,...,CYRENE AT MYSTIC FOOTHILLS,D R HORTON INC,"7689 E PINNACLE PEAK RD STE 20, SCOTTSDALE, AZ...",20250258867,05/06/2025,05/01/2025,"$12,960,000",NaN,NaN,51016307.html
1726982,51016308,", AZ",NaN,NaN,175341.0,175341 CYRENE AT MYSTIC FOOTHILLS,|,"2,058 sq ft.",NaN,PEORIA UNIFIED EXT 3,...,CYRENE AT MYSTIC FOOTHILLS,D R HORTON INC,"7689 E PINNACLE PEAK RD STE 20, SCOTTSDALE, AZ...",20250258867,05/06/2025,05/01/2025,"$12,960,000",NaN,NaN,51016308.html
1726983,51016309,", AZ",NaN,NaN,175341.0,175341 CYRENE AT MYSTIC FOOTHILLS,|,"1,640 sq ft.",NaN,NaN,...,CYRENE AT MYSTIC FOOTHILLS,D R HORTON INC,"7689 E PINNACLE PEAK RD STE 20, SCOTTSDALE, AZ...",20250258867,05/06/2025,05/01/2025,"$12,960,000",NaN,NaN,51016309.html
1726984,51016310,", AZ",NaN,NaN,175341.0,175341 CYRENE AT MYSTIC FOOTHILLS,|,"1,339 sq ft.",NaN,PEORIA UNIFIED EXT 3,...,CYRENE AT MYSTIC FOOTHILLS,D R HORTON INC,"7689 E PINNACLE PEAK RD STE 20, SCOTTSDALE, AZ...",20250258867,05/06/2025,05/01/2025,"$12,960,000",NaN,NaN,51016310.html
1726985,51016311,", AZ",NaN,NaN,175341.0,175341 CYRENE AT MYSTIC FOOTHILLS,|,"183,087 sq ft.",NaN,PEORIA UNIFIED EXT 3,...,CYRENE AT MYSTIC FOOTHILLS,D R HORTON INC,"7689 E PINNACLE PEAK RD STE 20, SCOTTSDALE, AZ...",20250258867,05/06/2025,05/01/2025,"$12,960,000",NaN,NaN,51016311.html

In [3]:
df2 = pd.read_csv(r"C:\Users\khushi.limbachiya\OneDrive\Documents\maricopa.csv")
df2

,OBJECTID,parcelnumb,owner,address,city,county,state2,szip,ll_gisacre,wkb_geometry_Length,wkb_geometry_Area,Shape.STArea(),Shape.STLength()
0,334001,21755226,MARK C BOEN AND VERONICA S BOEN LIVING TRUST,11535 E WHISPERING WIND DR,phoenix,maricopa,AZ,85255-5740,0.22841,NaN,NaN,8.996163e-08,0.001201
1,334002,21755607,CHRISTOPH LEE/SUSAN,10723 E WHISPERING WIND DR,phoenix,maricopa,AZ,85255-8079,0.22730,NaN,NaN,8.952450e-08,0.001226
2,334003,11614109,CARRETO BERTHA CANO,1634 E BRILL ST,phoenix,maricopa,AZ,85006-3011,0.16526,NaN,NaN,6.490238e-08,0.001120
3,334004,21754349,ARINI NICK,14815 N 94TH PL,phoenix,maricopa,AZ,85260-2899,0.16336,NaN,NaN,6.427300e-08,0.001026
4,334005,21847051,CAMPA SUSAN V,9050 E CHAMBERS ST,phoenix,maricopa,AZ,85208-2911,0.14930,NaN,NaN,5.859988e-08,0.000996
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726981,2057996,50041631,PENDING,NaN,phoenix,maricopa,AZ,85323,0.13145,NaN,NaN,5.159363e-08,0.001024
1726982,2057997,50041743,PENDING,NaN,phoenix,maricopa,AZ,85323,0.15472,NaN,NaN,6.072675e-08,0.001046
1726983,2057998,50045972,PENDING,439 S 3RD AVE,phoenix,maricopa,AZ,85323-2205,3.93506,NaN,NaN,1.544565e-06,0.005142
1726984,2057999,50041605,PENDING,NaN,phoenix,maricopa,AZ,85323,0.13182,NaN,NaN,5.173900e-08,0.000967
1726985,2058000,50041655,PENDING,NaN,phoenix,maricopa,AZ,85323,0.12690,NaN,NaN,4.980675e-08,0.000947

In [6]:
import pandas as pd
import numpy as np

df3_small = df2[['parcelnumb']].copy()
df3_small['parcelnumb'] = df3_small['parcelnumb'].astype(str)

df_small = df[['Parcel']].copy()
df_small['Parcel'] = df_small['Parcel'].astype(str)

result = (
    df3_small.merge(
        df_small,
        left_on="parcelnumb",
        right_on="Parcel",
        how="left",
        indicator=True
    )
)

result["status"] = np.where(
    result["_merge"] == "both",
    "Matched",
    "Not Matched"
)

result = result[["parcelnumb", "status"]]

print(result)

        parcelnumb   status
0         21755226  Matched
1         21755607  Matched
2         11614109  Matched
3         21754349  Matched
4         21847051  Matched
...            ...      ...
1726981   50041631  Matched
1726982   50041743  Matched
1726983   50045972  Matched
1726984   50041605  Matched
1726985   50041655  Matched

[1726986 rows x 2 columns]

In [8]:
result[result['status']=='Not Matched']

Empty DataFrame
Columns: [parcelnumb, status]
Index: []